### ISSUE TITLE
npm run dll

### ISSUE THREAD

**Issue by implll** [CyberFei/puzzle#19]
报错E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\class-utils\node_modules\define-property\index.js:1
(function (exports, require, module, __filename, __dirname) 
{SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at NativeCompileCache._moduleCompile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\class-utils\index.js:5:14)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\base\index.js:10:10)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\snapdragon\index.js:3:12)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puzzle_demo@0.2.1 core: `webpack --hide-modules --config config/webpack.build.core.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puzzle_demo@0.2.1 core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-07-08T10_09_19_804Z-debug.log

**Comment by implll** [comment]
E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\class-utils\node_modules\define-property\index.js:1
(function (exports, require, module, __filename, __dirname) {}

**Comment by implll** [comment]
SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at NativeCompileCache._moduleCompile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\class-utils\index.js:5:14)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\base\index.js:10:10)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\snapdragon\index.js:3:12)
    at Module._compile (E:\Workspace\vue模板\puzzle-master\puzzle-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puzzle_demo@0.2.1 core: `webpack --hide-modules --config config/webpack.build.core.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puzzle_demo@0.2.1 core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-07-08T10_09_19_804Z-debug.log

E:\Workspace\vue模板\puzzle-master\puzzle-master>npm install
npm WARN puzzle_demo@0.2.1 No repository field.
npm WARN puzzle_demo@0.2.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 11.384s

E:\Workspace\vue模板\puzzle-master\puzzle-master>npm run build

> puzzle_demo@0.2.1 build E:\Workspace\vue模板\puzzle-master\puzzle-master
> node config/webpack.prod.js

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '../static/dll/core.manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\Workspace\vue模板\puzzle-master\puzzle-master\config\webpack.common.js:65:17)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puzzle_demo@0.2.1 build: `node config/webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puzzle_demo@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-07-08T10_21_36_552Z-debug.log

**Comment by CyberFei** [comment]
这块应该没问题，检查一下自己的步骤吧，或者把项目手动下下来，尝试一下
